# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            mattjay
tagline:          'see description'
description:      'Web Application Security Researcher, wannabe developer, whiskey drinker, beer nerd, giant dog owner, Director of Security @<a href="https://honestdollar.com">HonestDollar</a>'
url:              http://mattjay.github.io

gems:
  - jemoji
  - jekyll-mentions

author:
  name:           'Matt Johansen'
  url:            https://twitter.com/mattjay
  
analytics :
  provider : google
  google : 
      tracking_id : 'UA-67980003-1'

paginate:         5

# Custom vars
version:          2.0.0

github:
  main:           https://github.com/mattjay/

twitter:
  main:           https://www.twitter.com/mattjay

linkedin:
  main:           http://www.linkedin.com/in/matthewjohansen
