# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            mattjay
tagline:          'see description'
description:      'Web Application Security Researcher, wannabe developer, whiskey drinker, beer nerd, giant dog owner, head of Threat Research Center @<a href="http://whitehatsec.com">whitehatsec</a> Houston, TX'
url:              http://mattjay.github.io

author:
  name:           'Matt Johansen'
  url:            https://twitter.com/mattjay

paginate:         5

# Custom vars
version:          2.0.0

github:
  main:           https://github.com/mattjay/

twitter:
  main:           https://www.twitter.com/mattjay

linkedin:
  main:           http://www.linkedin.com/in/matthewjohansen
